export enum KLScraperScrapConfigEnvVariable {
  KL_SCRAPER_SCRAP_CONFIG_OUTPUT_DIR = 'KL_SCRAPER_SCRAP_CONFIG_OUTPUT_DIR',
  KL_SCRAPER_SCRAP_CONFIG_RECIPES_PER_FILE = 'KL_SCRAPER_SCRAP_CONFIG_RECIPES_PER_FILE',
  KL_SCRAPER_SCRAP_CONFIG_START_CURSOR = 'KL_SCRAPER_SCRAP_CONFIG_START_CURSOR',
}
